### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by teh-masterer** [tjdavisbz/NiceHashToMQTT#4]
Hi, I'm also a programmer, but don't normally use Python at all. I tried running your script,  but it requires the files 'json' and 'requests'. Also it depends on having paho and some bitcoin library, how can I resolve this? Finding the files and adding them to the dir? Is there an automatic dependency resolver that I should have used?

**Comment by tjdavisbz** [comment]
You can use the pip installer to install the dependencies.
